// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksDirectory.Models;

namespace ParksDirectory.Solution.Migrations
{
    [DbContext(typeof(ParkContext))]
    [Migration("20220819174104_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksDirectory.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "If you enjoy scenic views of deep river canyons or rock climbing, Smith Rock State Park is the place for you. There are several thousand climbs in the park. More than a thousand are bolted routes. We also offer miles of hiking and mountain biking trails. Along your trip through the canyon, you might see golden eagles, prairie falcons, mule deer, river otter and beaver.",
                            Location = "Bend, OR",
                            Name = "Smith Rock State Park",
                            PhotoUrl = "https://openoregon.pressbooks.pub/app/uploads/sites/44/2018/10/Smith_Rock_in_the_Afternoon.jpg"
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "Wrapping around Tillamook Head, between Seaside and Cannon Beach, Ecola State Park stretches along 9 miles of coastline and offers outstanding sightseeing and recreation opportunities combined with a storied past.  Though the scenic and hiking opportunities may be the main allure, the diversity of outdoor recreation including picnicking, tidepooling, surfing and wildlife observation make Ecola State park a destination year round.",
                            Location = "Seaside, OR",
                            Name = "Ecola State Park",
                            PhotoUrl = "https://images.squarespace-cdn.com/content/v1/50f189dde4b07e77c464e9f3/1514820900691-0DQ7Z1FW5TCWN4HY4N6M/Cannon+Beach+View.jpg?format=1000w"
                        },
                        new
                        {
                            ParkId = 3,
                            Description = "Portland's signature park isn't just loaded with big trees and picnic tables. Located a mere two miles west of downtown and accessible by MAX light rail, 410-acre Washington Park offers up a zoo, two museums, a spectacular rose garden, one of the most authentic Japanese gardens in the world, all bordered by Forest Park — at 5,100 acres, one of the country's premier urban wildernesses.",
                            Location = "Portland, OR",
                            Name = "Washington Park",
                            PhotoUrl = "https://images.squarespace-cdn.com/content/v1/5665d770df40f3d958f69fd2/1594098580329-26S5U9BRCO5EGE79Z0PA/International+Rose+Test+Garden6.jpg"
                        },
                        new
                        {
                            ParkId = 4,
                            Description = "People call it the “crown jewel” of the Oregon State Parks system, and once you visit, you know why. Silver Falls State Park is the kind of standout scenic treasure that puts Oregon firmly onto the national—and international—stage. Its beauty, boundless recreational opportunities and historic presence keep it there.",
                            Location = "Salem, OR",
                            Name = "Silver Falls State Park",
                            PhotoUrl = "https://oregonisforadventure.com/wp-content/uploads/2020/06/silver-falls-state-park-trail-of-ten-falls.jpg"
                        },
                        new
                        {
                            ParkId = 5,
                            Description = "Mt. Hood National Forest offers a huge variety of world-class recreational activities with opportunities for everyone. Mt Hood National Forest encompasses eight unique Wilderness areas as well as multiple barrier free accessible sites to explore. Whether it's skiing, hiking, boating, rafting, climbing, backpacking, horseback riding, or fishing that you are hoping to experience, you're sure to find great opportunities in your National Forest. Camping in one of our developed campgrounds is a wonderful way to enjoy the forest. For reservations visit recreation.gov. Visit Portland General Electric for reservations at Lake Harriet or Timothy Lake.",
                            Location = "Government Camp, OR",
                            Name = "Mt. Hood Natl. Forest",
                            PhotoUrl = "https://media.istockphoto.com/photos/mount-hood-oregon-picture-id1268487061?k=20&m=1268487061&s=612x612&w=0&h=RJ1ZSwIVtEkQ8GRnOg7jD0iFH9msAjeIW9k7UmnjP1U="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
